### ISSUE TITLE
rtorrent failing after some hours. 

### ISSUE THREAD

**Issue by javydekoning** [ac1dburnz/rtorrent-rutorrent-cross-seed#129]
### App Name

rtorrent

### Operating System

Other Using Helm (please specify)

### App Version

ghcr.io/ac1dburnz/rtorrent-rutorrent-cross-seed:latest@sha256:febb2c4617a63ba0f2a61d17bb3b4e0c453f4ffe3221d566e1bca248fc3589a4

### Application Events

```Shell
N/A
```

### Application Logs

```Shell
10.42.0.149 - - [29/May/2024:03:02:41 +0200] "POST /RPC2 HTTP/1.1" 200 739114 "-" "Sonarr/4.0.4.1491 (alpine 3.19.1)"
10.42.0.161 - - [29/May/2024:03:02:41 +0200] "POST /RPC2 HTTP/1.1" 200 93178 "-" "NodeJS XML-RPC Client"
10.42.0.161 - - [29/May/2024:03:02:41 +0200] "POST /RPC2 HTTP/1.1" 200 334 "-" "NodeJS XML-RPC Client"
10.42.0.161 - - [29/May/2024:03:02:41 +0200] "POST /RPC2 HTTP/1.1" 200 140 "-" "NodeJS XML-RPC Client"
10.42.0.161 - - [29/May/2024:03:02:41 +0200] "POST /RPC2 HTTP/1.1" 200 93252 "-" "NodeJS XML-RPC Client"
10.42.0.161 - - [29/May/2024:03:02:47 +0200] "POST /RPC2 HTTP/1.1" 200 93252 "-" "NodeJS XML-RPC Client"
10.42.0.161 - - [29/May/2024:03:02:47 +0200] "POST /RPC2 HTTP/1.1" 200 334 "-" "NodeJS XML-RPC Client"
10.42.0.161 - - [29/May/2024:03:02:47 +0200] "POST /RPC2 HTTP/1.1" 200 140 "-" "NodeJS XML-RPC Client"
10.42.0.161 - - [29/May/2024:03:02:47 +0200] "POST /RPC2 HTTP/1.1" 200 93326 "-" "NodeJS XML-RPC Client"
10.42.0.161 - - [29/May/2024:03:02:51 +0200] "POST /RPC2 HTTP/1.1" 200 93326 "-" "NodeJS XML-RPC Client"
10.42.0.161 - - [29/May/2024:03:02:51 +0200] "POST /RPC2 HTTP/1.1" 200 334 "-" "NodeJS XML-RPC Client"
10.42.0.161 - - [29/May/2024:03:02:51 +0200] "POST /RPC2 HTTP/1.1" 200 140 "-" "NodeJS XML-RPC Client"
10.42.0.161 - - [29/May/2024:03:02:51 +0200] "POST /RPC2 HTTP/1.1" 200 93400 "-" "NodeJS XML-RPC Client"
2024/05/29 03:03:13 [warn] 590#590: *1526 a client request body is buffered to a temporary file /tmp/nginx/8/14/0000000148, client: 10.42.0.164, server: , request: "POST /RPC2 HTTP/1.1", host: "rutorrent-service:8000"
10.42.0.164 - - [29/May/2024:03:03:14 +0200] "POST /RPC2 HTTP/1.1" 200 140 "-" "Go-http-client/1.1"
10.42.0.148 - - [29/May/2024:03:03:25 +0200] "POST /RPC2 HTTP/1.1" 200 741629 "-" "Radarr/5.6.0.8846 (alpine 3.19.1)"
2024/05/29 03:03:26 [warn] 590#590: *1530 a client request body is buffered to a temporary file /tmp/nginx/9/14/0000000149, client: 10.42.0.164, server: , request: "POST /RPC2 HTTP/1.1", host: "rutorrent-service:8000"
2024/05/29 03:03:26 [warn] 590#590: *1532 a client request body is buffered to a temporary file /tmp/nginx/0/15/0000000150, client: 10.42.0.164, server: , request: "POST /RPC2 HTTP/1.1", host: "rutorrent-service:8000"
10.42.0.164 - - [29/May/2024:03:03:26 +0200] "POST /RPC2 HTTP/1.1" 200 140 "-" "Go-http-client/1.1"
2024/05/29 03:04:24 [warn] 590#590: *1536 a client request body is buffered to a temporary file /tmp/nginx/1/15/0000000151, client: 10.42.0.164, server: , request: "POST /RPC2 HTTP/1.1", host: "rutorrent-service:8000"
2024/05/29 03:04:26 [info] 590#590: *1532 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 10.42.0.164, server: , request: "POST /RPC2 HTTP/1.1", upstream: "scgi://unix:/var/run/rtorrent/scgi.socket:", host: "rutorrent-service:8000"
10.42.0.164 - - [29/May/2024:03:04:26 +0200] "POST /RPC2 HTTP/1.1" 499 0 "-" "Go-http-client/1.1"
2024/05/29 03:05:11 [error] 590#590: *1534 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.42.0.149, server: , request: "POST /RPC2 HTTP/1.1", upstream: "scgi://unix:/var/run/rtorrent/scgi.socket", host: "rutorrent-service:8000"
10.42.0.149 - - [29/May/2024:03:05:11 +0200] "POST /RPC2 HTTP/1.1" 504 160 "-" "Sonarr/4.0.4.1491 (alpine 3.19.1)"
2024/05/29 03:05:24 [error] 590#590: *1536 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.42.0.164, server: , request: "POST /RPC2 HTTP/1.1", upstream: "scgi://unix:/var/run/rtorrent/scgi.socket", host: "rutorrent-service:8000"
10.42.0.164 - - [29/May/2024:03:05:24 +0200] "POST /RPC2 HTTP/1.1" 504 160 "-" "Go-http-client/1.1"
2024/05/29 03:05:55 [error] 590#590: *1538 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.42.0.148, server: , request: "POST /RPC2 HTTP/1.1", upstream: "scgi://unix:/var/run/rtorrent/scgi.socket", host: "rutorrent-service:8000"
10.42.0.148 - - [29/May/2024:03:05:55 +0200] "POST /RPC2 HTTP/1.1" 504 160 "-" "Radarr/5.6.0.8846 (alpine 3.19.1)"
2024/05/29 03:06:16 [error] 590#590: *1540 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.42.0.149, server: , request: "POST /RPC2 HTTP/1.1", upstream: "scgi://unix:/var/run/rtorrent/scgi.socket", host: "rutorrent-service:8000"
```

### Application Configuration

N/A

### Describe the bug

After running for a few hours (~6 in the above example), rtorrent starts failing. When the container is restarted everything is fine again

### To Reproduce

N/A

### Expected Behavior

rtorrent to not fail and the healthcheck to work. 

Healthcheck works, but container is not restarted:

```sh
-> # k exec -it -n dvr rutorrent-deployment-76c7f845f6-8m9t7 -- /bin/sh/ # 
curl --fail -d "<?xml version='1.0'?><methodCall><methodName>system.api_version</methodName></methodCall>" http://127.0.0.1:8001
curl: (22) The requested URL returned error: 502
```

This seems to be on me, Kubernetes does not pickup the HEALTHCHECK from the Dockerfile. I'll move this to a liveness probe myself for now.

### Screenshots

N/A

### Additional Context

This has been happening for about a week, and I'm always running the latest version. I have not tried to move back to an older release just yet.

`rtorrent.log` shows no relevant info:

```
1716966318 N rtorrent main: Starting thread.
1716966318 N rtorrent scgi: Starting thread.
1716966325 N rtorrent main: Shutting down thread.
```

Not sure how to proceed with debugging this.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by javydekoning** [comment]
Could this be related to the reduced TCP buffer memsize? I'll move those back to 16M to test.

https://github.com/ac1dburnz/rtorrent-rutorrent-cross-seed/commit/6ce9cc7b173d0fe0a98498dfc9062467b90d9d61

**Comment by ac1dburnz** [comment]
@javydekoning I haven't had any issues with rtorrent restarting on truenas scale. Try to change the variable for RT_SEND_BUFFER_SIZE and RT_RECEIVE_BUFFER_SIZE  and let me know if it does help but this has been tested on scale.

**Comment by javydekoning** [comment]
Moved back to 16M and has been stable for the last 24 hours. I'll keep monitoring for a bit more.

**Comment by ac1dburnz** [comment]
if that is the case i can change its default

**Comment by javydekoning** [comment]
It hasn't failed ever since. Hence, closing the issue.

**Comment by ac1dburnz** [comment]
Hey, I'm really sorry to do this, but I think I'm going to archive this repository. TrueNAS Scale has decided to deprecate Helm charts. I was planning to stick with TrueCharts and migrate, but after dealing with them more, I have decided to move away from their product and stop using docker for rutorrent. If you want, I can add you as a contributor if you want to continue supporting the repository. But if not, I'm just going to archive it.

**Comment by ac1dburnz** [comment]
Hey @javydekoning , I'm really sorry to do this, but I think I'm going to archive this repository. TrueNAS Scale has decided to deprecate Helm charts. I was planning to stick with TrueCharts and migrate, but after dealing with them more, I have decided to move away from their product and stop using docker for rutorrent. If you want, I can add you as a contributor if you want to continue supporting the repository. But if not, I'm just going to archive it.

**Comment by javydekoning** [comment]
No worries @ac1dburnz , I'll try and move back to https://github.com/crazy-max/docker-rtorrent-rutorrent and make the needed modifications via initContainer

For what it's worth, I moved to k3s running in a jail on Truenas.

**Comment by ac1dburnz** [comment]
@javydekoning i was thinking that, but instead I ran it in a jail. I find the performance to be a lot better in the jail than in a docker container.

**Comment by ac1dburnz** [comment]
do you have discord by any chance? I might have an idea for you but rather not do it on here.

**Comment by ac1dburnz** [comment]
hey dude, just a heads up that im reopening this repo :)
